### PR TITLE
Fixes issue with qp-octets introduced by Outlook workaround

### PR DESCRIPTION
**Pull request by steffenweber**
https://github.com/zendframework/zend-mime/pull/4#issuecomment-213501293

### CODE REVIEW

**Comment by steffenweber** [comment]
Could you please merge this pull request and release a new version? As @eth8505 said in https://github.com/zendframework/zend-mime/pull/4#issuecomment-214489388, the current version unfortunately has real issues.

**Comment by steffenweber** [comment]
@weierophinney: Could you please merge this pull request?

**Comment by steffenweber** [comment]
@weierophinney: This pull request fixes a regression introduced by #4. Could you please merge this and release a new version?

**Comment by weierophinney** [comment]
Thanks, @steffenweber; will have a 2.6.1 release out today.

**Pull request merged**
